// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/home/teams": {
    params: {};
  };
  "/home/clubs": {
    params: {};
  };
  "/home/favourites": {
    params: {};
  };
  "/home/recent": {
    params: {};
  };
  "/club/:clubId": {
    params: {
      "clubId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/overview": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/matches": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/results": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/standings": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/match/:matchUuid": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
      "matchUuid": string;
    };
  };
  "/team/:clubId/:teamType/:teamId/poule": {
    params: {
      "clubId": string;
      "teamType": string;
      "teamId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/home/teams" | "/home/clubs" | "/home/favourites" | "/home/recent" | "/club/:clubId" | "/team/:clubId/:teamType/:teamId" | "/team/:clubId/:teamType/:teamId/overview" | "/team/:clubId/:teamType/:teamId/matches" | "/team/:clubId/:teamType/:teamId/results" | "/team/:clubId/:teamType/:teamId/standings" | "/team/:clubId/:teamType/:teamId/match/:matchUuid" | "/team/:clubId/:teamType/:teamId/poule";
  };
  "./App.tsx": {
    id: "App";
    page: "/" | "/home" | "/home/teams" | "/home/clubs" | "/home/favourites" | "/home/recent" | "/club/:clubId" | "/team/:clubId/:teamType/:teamId" | "/team/:clubId/:teamType/:teamId/overview" | "/team/:clubId/:teamType/:teamId/matches" | "/team/:clubId/:teamType/:teamId/results" | "/team/:clubId/:teamType/:teamId/standings" | "/team/:clubId/:teamType/:teamId/match/:matchUuid" | "/team/:clubId/:teamType/:teamId/poule";
  };
  "./pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "./pages/home/HomeLayout.tsx": {
    id: "pages/home/HomeLayout";
    page: "/home" | "/home/teams" | "/home/clubs" | "/home/favourites" | "/home/recent";
  };
  "./pages/home/TeamSearch.tsx": {
    id: "pages/home/TeamSearch";
    page: "/home/teams";
  };
  "./pages/home/ClubSearch.tsx": {
    id: "pages/home/ClubSearch";
    page: "/home/clubs";
  };
  "./pages/home/Favourites.tsx": {
    id: "pages/home/Favourites";
    page: "/home/favourites";
  };
  "./pages/home/Recent.tsx": {
    id: "pages/home/Recent";
    page: "/home/recent";
  };
  "./pages/club/Club.tsx": {
    id: "pages/club/Club";
    page: "/club/:clubId";
  };
  "./pages/team/TeamLayout.tsx": {
    id: "pages/team/TeamLayout";
    page: "/team/:clubId/:teamType/:teamId" | "/team/:clubId/:teamType/:teamId/overview" | "/team/:clubId/:teamType/:teamId/matches" | "/team/:clubId/:teamType/:teamId/results" | "/team/:clubId/:teamType/:teamId/standings" | "/team/:clubId/:teamType/:teamId/match/:matchUuid" | "/team/:clubId/:teamType/:teamId/poule";
  };
  "./pages/team/teamOverview/TeamOverview.tsx": {
    id: "pages/team/teamOverview/TeamOverview";
    page: "/team/:clubId/:teamType/:teamId/overview";
  };
  "./pages/team/teamMatches/TeamSchedule.tsx": {
    id: "pages/team/teamMatches/TeamSchedule";
    page: "/team/:clubId/:teamType/:teamId/matches";
  };
  "./pages/team/teamMatches/TeamResults.tsx": {
    id: "pages/team/teamMatches/TeamResults";
    page: "/team/:clubId/:teamType/:teamId/results";
  };
  "./pages/team/teamStandings/TeamStandings.tsx": {
    id: "pages/team/teamStandings/TeamStandings";
    page: "/team/:clubId/:teamType/:teamId/standings";
  };
  "./pages/team/match/MatchPage.tsx": {
    id: "pages/team/match/MatchPage";
    page: "/team/:clubId/:teamType/:teamId/match/:matchUuid";
  };
  "./pages/team/poule/PoulePage.tsx": {
    id: "pages/team/poule/PoulePage";
    page: "/team/:clubId/:teamType/:teamId/poule";
  };
};

type RouteModules = {
  "root": typeof import("./frontend/src/root.tsx");
  "App": typeof import("./frontend/src/./App.tsx");
  "pages/Index": typeof import("./frontend/src/./pages/Index.tsx");
  "pages/home/HomeLayout": typeof import("./frontend/src/./pages/home/HomeLayout.tsx");
  "pages/home/TeamSearch": typeof import("./frontend/src/./pages/home/TeamSearch.tsx");
  "pages/home/ClubSearch": typeof import("./frontend/src/./pages/home/ClubSearch.tsx");
  "pages/home/Favourites": typeof import("./frontend/src/./pages/home/Favourites.tsx");
  "pages/home/Recent": typeof import("./frontend/src/./pages/home/Recent.tsx");
  "pages/club/Club": typeof import("./frontend/src/./pages/club/Club.tsx");
  "pages/team/TeamLayout": typeof import("./frontend/src/./pages/team/TeamLayout.tsx");
  "pages/team/teamOverview/TeamOverview": typeof import("./frontend/src/./pages/team/teamOverview/TeamOverview.tsx");
  "pages/team/teamMatches/TeamSchedule": typeof import("./frontend/src/./pages/team/teamMatches/TeamSchedule.tsx");
  "pages/team/teamMatches/TeamResults": typeof import("./frontend/src/./pages/team/teamMatches/TeamResults.tsx");
  "pages/team/teamStandings/TeamStandings": typeof import("./frontend/src/./pages/team/teamStandings/TeamStandings.tsx");
  "pages/team/match/MatchPage": typeof import("./frontend/src/./pages/team/match/MatchPage.tsx");
  "pages/team/poule/PoulePage": typeof import("./frontend/src/./pages/team/poule/PoulePage.tsx");
};